name: Analyze
on:
  issue_comment:
    types: [created]

jobs:
  slow-query-log:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: unnecessary
          config: |
            Host isucon
              HostName 35.77.214.139
              User root
              Port 22
              StrictHostKeyChecking no
              IdentityFile ~/.ssh/id_rsa
      - name: Create output file
        run: echo "Create PR comment successfully!" > output.txt
      - name: Comment PR
        uses: shellingford330/pr-comment-action@v0.0.4
        with:
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.issue.number }}
          filepath: output.txt
          template: |
            <details>
            <summary>Show Output</summary>

            ```
            {{ . }}
            ```

            </details>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
