name: Log Analysis
on:
  issue_comment:
    types: [created]

jobs:
  analyze:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/analyze') }}
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: unnecessary
          config: |
            Host isucon
              HostName 35.78.206.73
              User root
              Port 22
              StrictHostKeyChecking no
              IdentityFile ~/.ssh/id_rsa
      - name: Analyze
        run: |
          ssh isucon 'make analyze'
      - name: Pull analysis result
        run: |
          rsync -av isucon:~/pt_query_digest_analysis.txt ./
          rsync -av isucon:~/mysqldumpslow_analysis.txt ./
          rsync -av isucon:~/alp_analysis.txt ./
      - name: Create pt-query-digest comment on PR
        uses: shellingford330/pr-comment-action@v0.0.6
        with:
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.issue.number }}
          filepath: pt_query_digest_analysis.txt
          template: |
            Analyze slow query log by pt-query-digest.
            <details>
            <summary>Show Analisys Result</summary>

            ```
            {{ . }}
            ```

            </details>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create mysqldumpslow comment on PR
        uses: shellingford330/pr-comment-action@v0.0.6
        with:
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.issue.number }}
          filepath: mysqldumpslow_analysis.txt
          template: |
            Analyze slow query log by mysqldumpslow.
            <details>
            <summary>Show Analisys Result</summary>

            ```
            {{ . }}
            ```

            </details>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create alp comment on PR
        uses: shellingford330/pr-comment-action@v0.0.6
        with:
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.issue.number }}
          filepath: alp_analysis.txt
          template: |
            Analyze access log by alp.
            <details>
            <summary>Show Analisys Result</summary>

            ```
            {{ . }}
            ```

            </details>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
