name: CD
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: unnecessary
          config: |
            Host isuconapp
              HostName ${{ secrets.APP_HOST_NAME }}
              User root
              Port 22
              StrictHostKeyChecking no
              IdentityFile ~/.ssh/id_rsa
            Host isucondb
              HostName ${{ secrets.DB_HOST_NAME }}
              User root
              Port 22
              StrictHostKeyChecking no
              IdentityFile ~/.ssh/id_rsa
      - name: Deploy
        run: sh deploy.sh
